on:
    workflow_dispatch:
    schedule:
        - cron: '0 12 * * *'

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - run: npm ci
            - run: npm start
            - run: ./commit.sh
